### ISSUE TITLE
Updated README

### ISSUE THREAD

**Issue by alopezm** [alopezm/coming-site-express#7]
The README.md file is incomplete. Update with all the necessary required components.
See the following links for help to write README files:
http://jfhbrook.github.io/2011/11/09/readmes.html
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by ksreenivasan** [comment]
@alopezm : I would like to take this up.

**Comment by alopezm** [comment]
@kamikazekartik yes of course, please create a new branch and then a pull request. Let me know if you need any detail or help.

**Comment by ksreenivasan** [comment]
@alopezm: I've created a pull request [here](https://github.com/alopezm/coming-site-express/pull/13). Do check it out and let me know if you need any other changes. 
This is my first pull request so tolerate some noobness please! 😃

**Comment by alopezm** [comment]
@kamikazekartik nice work, can you please check the comments.

**Comment by alopezm** [comment]
@kamikazekartik than you for your help.
